version: "3.7"
services:
  fr24feed-piaware:
    image: "thomx/fr24feed-piaware"
    restart: unless-stopped
    environment: 
      - "FR24FEED_FR24KEY=6a011a367ce74815"
      - "PIAWARE_FEEDER_DASH_ID=a4abd523-354a-4496-9305-ac3e24a12566"
      - "HTML_SITE_LAT=37.74461"
      - "HTML_SITE_LON=-122.42568"
      - "HTML_SITE_NAME=MY_SITE_NAME"
      - "HTML_DEFAULT_TRACKER=Flightradar24"
      - "HTML_RECEIVER_STATS_PAGE_FLIGHTAWARE=https://flightaware.com/adsb/stats/user/"
      - "HTML_RECEIVER_STATS_PAGE_FLIGHTRADAR24=https://www.flightradar24.com/account/feed-stats/?id=17995"
      - "HTML_FR24_FEEDER_STATUS_PAGE=http://raspberrypi:8754/"
      - "PANORAMA_ID=MY_PANORAMA_ID"
    devices:
      - "/dev/bus/usb"
    logging:
      options:
        max-size: "30m"
    # ports
    # 8754 - DUMP1090 server port
    # 8080 - HTTP server port
    ports:
      - "8754:8754"
      - "8080:8080"
    labels:
      - "traefik.http.routers.fr24feed-piaware-kube.rule=Host(`skyview`)"
    networks:
      - traefik_default
networks:
  traefik_default:
    external: true
